# Generated by Django 2.2.16 on 2022-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220415_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='Genre', to='reviews.Genre'),
        ),
    ]
