# Generated by Django 2.2.16 on 2022-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
